<<<<<<< HEAD
=======
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
>>>>>>> main
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
<<<<<<< HEAD
  ...(process.env.DATABASE_URL
    ? { datasource: { url: process.env.DATABASE_URL } }
    : {}),
=======
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use unpooled connection for migrations (required for schema operations)
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
>>>>>>> main
});
