// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
// @ts-ignore prisma config runs in Node via Prisma CLI and supports dotenv side-effect loading
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use unpooled connection for migrations (required for schema operations)
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
