name: Bug report
about: Report a defect or regression
labels: ["status:triage", "type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
