name: Feature request
about: Propose a product or engineering feature
labels: ["status:triage", "type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user/business problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Include architecture boundary considerations and tenancy/security implications.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define measurable criteria and test expectations.
    validations:
      required: true
