name: Performance Instrumentation (Milestone 8)
description: Track platform-level instrumentation and latency regression guardrails.
title: "[M8][PERF-001]: "
labels:
  - type:infra
  - domain:ci
  - scope:ci
  - p1
body:
  - type: markdown
    attributes:
      value: |
        Use this template for the dedicated Milestone 8 performance instrumentation issue.

  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: Keep this value as M8 for performance instrumentation governance.
      value: M8
    validations:
      required: true

  - type: textarea
    id: instrumentation_scope
    attributes:
      label: Instrumentation Scope
      description: Define exact endpoints/actions and metrics that must be instrumented.
      placeholder: |
        app/(tenant)/wraps/page.tsx p50/p95/p99, visualizer actions latency histograms, fallback success counters.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (Blocking)
      description: Include CI-failing criteria when metrics export/regression checks are missing or SLA thresholds fail.
      placeholder: |
        - CI fails if perf artifacts are missing.
        - CI fails if p95 thresholds are exceeded.
        - No PII in metrics labels.
    validations:
      required: true

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan
      description: Add specific script/harness tasks and dashboard/export tasks.
      placeholder: |
        1. Add perf harness command entries.
        2. Emit metrics artifacts under tests/perf/results.
        3. Wire pnpm perf:assert into CI.
    validations:
      required: true
