export const visualizerPreviewDTOFields = {
    id: true,
    wrapId: true,
    uploadId: true,
    processedImageUrl: true,
    status: true,
    cacheKey: true,
    referenceSignature: true,
    generationMode: true,
    generationProvider: true,
    generationModel: true,
    generationPromptVersion: true,
    generationFallbackReason: true,
    expiresAt: true,
    createdAt: true,
    updatedAt: true,
    upload: {
        select: {
            id: true,
            legacyUrl: true,
            cloudinaryPublicId: true,
            cloudinaryVersion: true,
            cloudinaryResourceType: true,
            cloudinaryDeliveryType: true,
            format: true,
            mimeType: true,
            width: true,
            height: true,
            createdAt: true,
            updatedAt: true,
        },
    },
    resultLegacyUrl: true,
    resultCloudinaryPublicId: true,
    resultCloudinaryVersion: true,
    resultCloudinaryResourceType: true,
    resultCloudinaryDeliveryType: true,
    resultFormat: true,
} as const

export const visualizerUploadSnapshotFields = {
    id: true,
    mimeType: true,
    width: true,
    height: true,
    createdAt: true,
    updatedAt: true,
    legacyUrl: true,
    cloudinaryPublicId: true,
    cloudinaryVersion: true,
    cloudinaryResourceType: true,
    cloudinaryDeliveryType: true,
    format: true,
} as const
